### ISSUE TITLE
Suggestion: Use Waveform format and enable use without ffmpeg

### ISSUE THREAD

**Issue by TheFlagCourier** [sudofox/melee.sh#1]
Just a small suggestion to enable usage _without_ ffmpeg, provided one of the following commands is available on the system: `aplay`, `paplay`, `pw-play`. If the mp3 files are changed to a waveform format (`success.wav`), they can be played directly with any of these.

This would allow easier integration on systems where ffmpeg may need to be installed from a 3rd party or built from source. This creates an out-of-the box experience for some users.

**Comment by sudofox** [comment]
I'll look into it

I've been sick and about an hour after I pushed to the repo, I got really sick so I'm out of commission for a day or two, hopefully not covid

**Comment by TheFlagCourier** [comment]
Sorry to hear that.

I can report that all three work when replacing `ffplay`, so you may be seeing a PR ;)

**Comment by sudofox** [comment]
Sure, that'd be cool!

It got worse, I'm in the hospital now. I'll still check github though
